### PR TITLE
Added linear gradients to the background. Solved #46

### PR DESCRIPTION
**Pull request by dipanshparmar**
# Description
Made the site's background more attractive. Fixed low contrast problem on the main theme.

# Type of Change:
deleted unnecessary images that are no longer required because in place of them now it is gradient colors.

- Code
- Quality Assurance
- User Interface

# Screenshots
Screenshots of the proposed changes compared with the current version of the project.
## main theme
image

## dark theme
image

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests/screenshots(If any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by dipanshparmar** [comment]
@Aakansha99 Please have a look at the changes.

**Comment by Pawansinghla** [comment]
you code has conflicts , please review the code.

**Comment by dipanshparmar** [comment]
Done!

**Comment by dipanshparmar** [comment]
> you code has conflicts , please review the code.

Done!

**Pull request closed without merging**
