### PR TITLE
Made Responsive

### LINKED ISSUE #38: Make the site responsive

### PR DESCRIPTION
**Pull request by Mitali-laroia**
Added meta tag and adjusted the div elements according to the sreen width.

# Description
The meta tag in index.html adjust the width as well as the orientation of the different div elements according to the screen width where we are viewing the project.

Fixes #38 # Type of Change:
- Code

# Screenshots
Screenshots of the proposed changes compared with the current version of the project
Screenshot (143)
Screenshot (144)
Screenshot (145)
Screenshot (146)

# Checklist:

- [1 ] My code follows the style guidelines(Clean Code) of this project
- [2 ] I have performed a self-review of my own code
- [ 3] I have added screenshots that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Mitali-laroia** [comment]
@Aakansha99 hello,please have a look on my PR and inform me if it is sufficient enough to get merged.

**Comment by Aakansha99** [comment]
your code has some conflicting files, please review it once

**Comment by Mitali-laroia** [comment]
@Aakansha99 I have resolved the conflict please check and inform me if any modifications required. Thank you.

**Comment by Mitali-laroia** [comment]
@Aakansha99 please review my pull request.

**Comment by Aakansha99** [comment]
It is still having some conflicts. Please have a look on it

**Comment by Mitali-laroia** [comment]
@Aakansha99  Resolved. Sorry for the inconvenience.

**Comment by Aakansha99** [comment]
Nice work:)

**Pull request merged**
