### PR TITLE
Update README.md #7

### PR DESCRIPTION
**Pull request by Aayushi-Mittal**
# Description
Improved README.md, aligned contents to center and some other changes

Fixes # 7

# Type of Change:
- Documentation

# Screenshots
Screenshot (951)
Screenshot (952)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests/screenshots(If any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Aakansha99** [comment]
Please resolve these merge conflicts

**Comment by Aayushi-Mittal** [comment]
Resolved the conflicts.

**Comment by Aakansha99** [comment]
There are some more conflicts, resolve them

**Comment by Aayushi-Mittal** [comment]
Now resolved the conflicts. Please merge it so that I can synchronize my forked repo with the main repo and can work on another issue as well. Thank You :)

**Pull request merged**
