### PR TITLE
solved #43 Code refactoring : seperate directory

### LINKED ISSUE #43: Creating a spearate directory and moving codes to separate files
**Describe the bug**

Right now all files are there in the same directory. I will create a separate directory for :

1. CSS files
2. Javascript files
3. assets -> images and other stuff.
(will change the file path in the code accordingly.)

So that the maintenance of the code is easier for everyone.

### PR DESCRIPTION
**Pull request by sameersrivastava13**
# Description
Added separate directory to make it look more clean and for easy management.
1. CSS files
2. Javascript files

Fixes #43 

# Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests/screenshots(If any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Git-Harshit — COMMENTED** [review]
Nicely segregated the files into respective folders. +1 on that 👍 . 
LGTM (Looking Good To Me)

I hope it was merged at earliest. It allows new users to access respective files at ease.

However, for now I would request moderators that this commit shall be merged after all other open pull requests with code changes are dealt with, or else they would face merge conflicts.

**Comment by Git-Harshit** [comment]
@sameersrivastava13 If you've contributed in it as a part of **HakinCodes 2020**, then make sure to request @Aakansha99 to add _CH20_ and other required labels to issue #43,  before this PR gets merged against it.

**Comment by sameersrivastava13** [comment]
> @sameersrivastava13 If you've contributed in it as a part of **HakinCodes 2020**, then make sure to request @Aakansha99 to add _CH20_ and other required labels to issue #43, before this PR gets merged against it.

Hi @Git-Harshit . I have mentioned @Aakansha99  many times to review this code and merge as soon as possible. But i guess she is offline from past few days.
Yes  i have contributed as a part of HakinCodes 2020, if you are a mentor then please add the required labels and merge the code asap.

**Comment by Git-Harshit** [comment]
>Hi @Git-Harshit . I have mentioned @Aakansha99 many times to review this code and merge as soon as possible. But i guess she is offline from past few days.
Yes i have contributed as a part of HakinCodes 2020, if you are a mentor then please add the required labels and merge the code asap.

Hi @sameersrivastava13, I won't be able to help you since I do not have any write access to this repository. We'll have to wait for @Aakansha99 to get back and take further action on the issues and PRs in this repository.

**Comment by Aakansha99** [comment]
Yeah you did nice work. There got some branch conflicts. Please have a look on it once

**Pull request closed without merging**
