### PR TITLE
Enhance site interface with CSS to more clearer and cleaner one, and minor site enhancements

### LINKED ISSUE #57: The current theme needs visual tweaks and enhancements for a clearer and better interface.
**Description of the enhancement**
The current public version of website lacks clear view, specially in light (non-dark) mode. Also, certain contents in the [hosted site](https://aakansha99.github.io/Github-Profile-Analyser/) (as on 1st September, 2020) can be more better distinguishable. 

**Screenshots**
Here's a pic to how it currently looks.
Capture_Unclear

As you can see, the user needs to have increased screen brightness and a very clear vision in order to actually see the entire directory at ease. 

So, I hope to see this getting fixed as soon as possible.

### PR DESCRIPTION
**Pull request by Git-Harshit**
This commit adds improved looks to the light (non-dark) theme specifically, by lightening the background. Also, the theme toggler now indicates the current theme when toggled.
Alongside, the commit now sets clickable links for user profiles followers, following, public repositories, and starred content. It also adds two headings to user profile details: users GitHub Pages hosted website, and Bio (About User). 
This PR is made in response to Issue #57.

# Description
The updated code mainly aims at enhancing the site appearance, fixing issues like invisibility of darker text over darker section.
Also, it involves minor code and performance improvisations.

Resolves #57 

# Type of Change:

- User Interface
- Minor Code Refactoring and functionality enhancement.

# Screenshots
Screenshots of the proposed changes compared with the current version.

Capture_Default-BG-Lightened
* Here, you can see that the default theme is more lightened than before, which eases readability of black text over it, in light theme. 

Capture_Light-BG-New-Looks
* The Light Theme Background previously set now seems to be a good choice and a good fit for the light theme, visually better appealing than before.

Capture_Dark_Theme
* Here's how the dark theme looks on home page. Also notice the text of theme toggler to be changed to dark theme.  

Capture_Theme_Button_OnHover
* This is the newer look of the theme toggler when hovered (placed a mouse over it) on home page. 

Capture_Buttons_OnHover
* This is the newer look of the buttons when hovered on home page. 

Capture_Profile_Clickables
* Check out the direct links that are made available for followers, following, repositories and stars tabs. 

Profile_Comparison
* Introducing optional column (named Custom Site)! Notice that it is visible only for those who have setup a custom site, hosted at their respective GitHub Page (In the image, it is available at 3rd row for the profile at right, whereas it isn't detected, and therefore the row is ommitted, for the profile at left). 

For older versions, of the displayed snippets, please check out the current version (before this PR is merged) of the [project](https://aakansha99.github.io/Github-Profile-Analyser/).

#### Additional Note:
<del> Please add relevant labels to issue #57 like _CH20_, _enhancement_, and others (if not yet added, @Aakansha99) before merging this PR against the issue. </del> It is all set, thanks to the repo owner!

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests/screenshots(If any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Aakansha99** [comment]
Please add screenshots for the same

**Comment by Git-Harshit** [comment]
@Aakansha99, I have updated the PR description with added screenshots, and have also resolved a merge conflict with index.html file of base branch. Please have a look at it now.

**Review by Git-Harshit — COMMENTED** [review]
@Aakansha99 The PR for the repository is now all set to enhance the site performance.

On merging my changes with your current live code (as on 5 Sept., 2020), here's how the updated version may look like:
a

Rest all is same as in description. 

Please look into the PR, and if everything looks perfect, then merge it into the main branch. For issues or anything other, please let me know!

**Comment by Git-Harshit** [comment]
Please let me know if the PR could be accepted and merged with the base branch, I'll fix the branch conflicts, just again. 
Else, feel free to close the PR.

**Comment by Pawansinghla** [comment]
please resolve these merge conflicts

**Pull request closed without merging**
