### PR TITLE
added a login button

### PR DESCRIPTION
**Pull request by ag278**
# Description
I have added a login button in the page for the pre-registered users

Fixes # [ISSUE]
 #20 

# Type of Change:

- Quality Assurance
- User Interface

# Screenshots
WhatsApp Image 2020-08-20 at 10 15 26 PM
WhatsApp Image 2020-08-20 at 10 15 26 PM (1)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests/screenshots(If any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ag278** [comment]
@Aakansha99 i have added the changes. Please check it once

**Review by Git-Harshit — APPROVED** [review]
The Log In Button looks nice to me, and the green btn-success fits well with the signup button.
👍 LGTM (Looks Good To Me) : )

**Comment by ag278** [comment]
@Git-Harshit  @Aakansha99  if there is no error could you please merge my pull request?

**Comment by Aakansha99** [comment]
It is having some branch conflicts. Please have a look on it

**Comment by ag278** [comment]
@Aakansha99 merge conflict is now resolved. Please check it and if there is no error please merge it

**Comment by Aakansha99** [comment]
Nice work:)

**Pull request merged**
