### PR TITLE
Icon color changed

### LINKED ISSUE #44: Icons in the main page
**Description of the enhancement**
Icons on the main page aren't much visible.

**Screenshots**
Current View:
Annotation 2020-08-21 091708

Modification:
Annotation 2020-08-21 091833

@Aakansha99  please assign me this issue.

### PR DESCRIPTION
**Pull request by Sapna2001**
# Description
Icons on the main page made white.

Fixes #44 

# Type of Change:
- Code
- Quality Assurance
- User Interface

# Screenshots
Annotation 2020-08-21 091833

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests/screenshots(If any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Aakansha99** [comment]
Please resolve these branch conflicts

**Comment by Pawansinghla** [comment]
@Sapna2001 
first resolve these conflicts

**Comment by Sapna2001** [comment]
Screenshot

Screenshot 2020-09-15 211323

**Comment by Sapna2001** [comment]
@Aakansha99  @Pawansinghla  I have fixed the conflicts.

**Pull request closed without merging**
